"""Add product gallery specifications and SEO fields

Revision ID: 502d37cede17
Revises: 8c8b03ee4972
Create Date: 2026-09-13 12:01:41.965364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502d37cede17'
down_revision = '8c8b03ee4972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('product_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_specifications_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('seo_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default='1', nullable=False))
        batch_op.alter_column('featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('best_seller',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('new_arrival',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.drop_constraint(batch_op.f('fk_products_service'), type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_products_service'), 'services', ['service_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.alter_column('new_arrival',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('best_seller',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('active')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('sku')

    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_specifications_product_id'))

    op.drop_table('product_specifications')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    # ### end Alembic commands ###
