"""Add category relationship to products

Revision ID: 8b75a4df5a4c
Revises: 25e331658ab5
Create Date: 2026-08-01 15:47:57.600180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b75a4df5a4c'
down_revision = '25e331658ab5'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('products', schema=None) as batch_op:

        batch_op.add_column(
            sa.Column(
                'category_id',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.create_foreign_key(
            'fk_products_category',
            'categories',
            ['category_id'],
            ['id']
        )
   
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
